basiljs/basil.js

- roadmap.txt
Like we decided on our meeting. Here is the roadmap draft for things to come.
> added roadmap for development

- includes/color.js
This fixes #73 by searching in the doc's color collection instead of the swatches. Made the argument checks and the colorMode checks stricter and improved formatting.
This passes `/test/all-tests.jsx`.
Please review.
> b.color() - bug fix and minor improvements

- .gitignore
These files should never go into version control. Taken from https://github.com/github/gitignore/blob/master/Node.gitignore
> chore(npm): added common npm/node development files to .gitignore

- scripts/examples/document/nameOnPage.jsx
- scripts/examples/input/shellExecute.jsx
- scripts/examples/typography/linkTextFrames.jsx
- scripts/examples/typography/text.jsx
- scripts/examples/typography/textAlign.jsx
- scripts/examples/typography/typo.jsx
When committing these files to git the linefeeds are not recognized so the whole commit creates one single line for the file.
This is maintenance only and can be merged right away.
> fix(BOM and CR): fixed some utf-8 bom files with windows CR

- README.md
- basil.js
- src/main.js
added links to trych me into head of script.  
This is maintenance.
> docs(README and head): Fixed a typo in head and README

- basil.js
- src/includes/color.js
Came across this redundant code and gave it a quick fix.
This can be merged right away.
> Minor code cleanup

- basil.js
- src/main.js
- test/all-tests.jsx
- test/arc-tests.jsx
- test/benchmarks/clearItems.jsx
- test/benchmarks/line_over_word.jsx
- test/benchmarks/pages with text + lines.jsx
- test/color-tests.jsx
- test/conversion-tests.jsx
- test/environment-tests.jsx
- test/group-tests.jsx
- test/input-tests.jsx
- test/string-tests.jsx
- test/typography-tests.jsx
- test/vertex-tests.jsx
- test/visual/canvasModes.jsx
This has been bothering me for a long time.  
Changed the # to @ in main.js and all test.  
All test passing:  
```text
58 test cases run
289 assertions run
289 passed
0 failed
```
Test files could use some linting. Examples still need to be changed.  
I also noticed that some of the benchmarking tests where linking to the "release" location of Basil. I changed that so they point to the local version.
> Move from # to @

- changelog.txt
Added changelog infos. Is it okay like this for you? If so I'll go ahead and merge right away.
> docs(changelog): added latest changes to changelog

- scripts/examples/template.jsx
- scripts/tutorials/advanced/05_connect_all_layer_elements/05_1.jsx
- scripts/tutorials/basic/02_Confetti/02_3.jsx
- scripts/tutorials/basic/02_Confetti/02_4.jsx
- scripts/tutorials/basic/04_Remixer/04_1.jsx
- scripts/tutorials/basic/05_FunctionPlotter/05_1.jsx
Ugh. There were *still* some files with broken line endings that did not display correctly in GitHub. This included `template.jsx` which consequently made every derived file from that file broken, which turned out to be quite the annoying issue in my class. 😞
I guess Fabian has a point to write all files from scratch. 😝
As this does not change the functions of the files itself, I will take the freedom to just merge this myself right away.
> Fixed line endings in the remaining broken files

- src/includes/environment.js
- src/includes/image.js
- src/includes/shape.js
- src/includes/typography.js
the with statement made problems with documentation creation. Removed it.
close #163  
```txt
58 test cases run
289 assertions run
289 passed
0 failed
Ergebnis: 58 test cases run
289 assertions run
289 passed
0 failed
```
> fix(with): removed `with` from 4 files

- src/includes/data.js
- src/includes/environment.js
- src/includes/global-functions.js
Improving some function comments. Issue for further improvements will follow
> improving jsdocs

- basil.js
- src/includes/math.js
@fabiantheblind here we go! :) All test passing. Should we really review this or simply merge?
> Fixed, added and improved jsDocs of math.js

- doc/api.json
- src/includes/math.js
minor fix. `.` created problems.
> . after noiseDetail created null entry in method

- basil.js
- src/includes/structure.js
some comment changes and linting.
> Jsdoc structure

- basil.js
- doc/api.json
- src/includes/transformation.js
The `Matrix2D` class still needs a lot of description. Still I reviewed all the JSDoc comments and did some linting.  All test passing.
> Jsdoc transformation

- src/includes/transformation.js
The @method name is currently needed.
> Added needed method names

- basil.js
- src/includes/transformation.js
> removed doubled infos

- basil.js
- src/includes/environment.js
- src/includes/math.js
of all my jsdoc files: 
environment.js
global-functions.js
image.js
math.js
> removed "optional" from jsDocs parameter descs

- basil.js
- changelog.txt
Hey guys,
this adds the missing stuff from the last b.swatch() commit. It adds the basil.js bundle and mentions `b.swatch()` in `changelog.txt`. Could somebody merge this quickly? I committed this in preparation of a larger PR that I would like to create soon. :)
Thanks!
P.S.: Not sure, why git messes up the diffs of the old basil.js and the new one, but the new one is just the bundled version of the source files, so it should be fine.
> Bundled basil.js and added missing b.swatch() mention to changelog

- src/includes/data.js
- src/includes/environment.js
- src/includes/global-functions.js
- src/includes/math.js
- src/includes/shape.js
- src/includes/transformation.js
🤖  kill all ~~humans~~ todos!
🤖  kill all ~~humans~~ todos!
🤖  kill all ~~humans~~ todos!
related to #193
> Kill todos

- basil.js
The bundle was not updated yet from the recent (well, "recent") todo-killing update. This updates the bundle, I will merge this right away, as the changes themselves have been reviewed.
> Updating bundle

- basil.js
- changelog.txt
- src/includes/data.js
- src/includes/environment.js
This is a quick and easy one, allowing `b.pageCount()` to be used as a setter, as we discussed in #136.
Please review. 🐛 🔍
> pageCount can be used as setter now

- basil.js
- src/includes/data.js
Cleanup of `b.projectFolder()`.
> Cleaned up b.projectFolder()

- basil.js
- changelog.txt
- src/includes/core.js
- src/includes/data.js
- src/includes/environment.js
- src/includes/image.js
- src/includes/private-vars.js
This adds functionality for files and folders, as discussed in #144. I gave this some intensive testing, it's actually quite fun to work with.
Here are the new methods and how to use them:
Gets a file or creates a file for later export.
```js
// Get an image file from the desktop and place it in the document
var myImage = b.file("~/Desktop/myImage.jpg");
b.image(myImage, 0, 0);
```
```js
// Create a file and export it to the desktop
var myExportFile = b.file("~/Desktop/myNewExportFile.pdf");
b.savePDF(myExportFile);
```
Gets a folder or creates one for later use.
```js
// Get a folder from the desktop and load its files
var myImageFolder = b.folder("~/Desktop/myImages/");
var myImageFiles = b.files(myImageFolder);
```
```js
// Get the data folder, if the document is already saved
var …
```
> Files and Folders

- basil.js
- package-lock.json
- package.json
- src/includes/environment.js
Back after a break.
This implements the proposed `property()` method, as was [discussed](https://github.com/basiljs/basil.js/wiki/Basil.js-Team-Call-Summary#bproperty) in our Skype talk a while back. It basically serves as a wrapper of JavaScripts dot-notation with some extra error checking and the ability to use an object with key value pairs to set several properties at once.
See added docs and examples for usage.
> property() method

- basil.js
- changelog.txt
- src/includes/document.js
`removePage()` now also works with page names.
> Updated removePage() to work with page names

- basil.js
- changelog.txt
- src/includes/document.js
`pageNumber()` now also can use a page name as input.
> pageNumber() update

- basil.js
- changelog.txt
- src/includes/image.js
- src/includes/typography.js
As discussed in #145, this allows placing images in text frames and text into shapes or onto graphic lines (as text paths).
Syntax:
```js
text(txt, obj);
image(imgFile, obj);
```
Added some examples to the `text()` function.
> Image text placing

- basil.js
- src/includes/document.js
> Added setter functionality to label()

- basil.js
- src/includes/document.js
Updated to leave the user on the page they were on if within the new `pageCount()`.
> Develop pagecount fix

- basil.js
- src/includes/color.js
- src/includes/data.js
- src/includes/document.js
- src/includes/environment.js
- src/includes/image.js
- src/includes/input.js
- src/includes/math.js
- src/includes/output.js
- src/includes/shape.js
- src/includes/structure.js
- src/includes/transform.js
- src/includes/typography.js
This adds summaries for all functions to be used in the restructured reference page. Will merge right away.
> @summary tags for inline docs
