includes/image.js

This fixes and improves b.image().
- there was no error handling, when wrong parameters were passed. Now, meaningful error messages are given: a `imgErrorMsg` explains possible options to the user. 
- there was a bug (that was not "issued" yet) that gave a wrong image size when using `b.image(img, x, y)` with `b.imageMode(b.CORNERS)`. This was fixed now, it now imports the image in its original size at the provided corner, as the method description would let you expect it.
- throws an error now if `w` or `h` are not greater than `0` when using `b.image(img, x, y, w, h)` with `b.imageMode(b.CORNER)`.
- updates the method doc to make more clear that you cannot use `b.image(img, x)`, but have to use `b.image(img, x, y)` (as there was some confusion about this). However, even if the user uses …

b.image() - bug fix and added error handling

---

includes/environment.js

- sets active layer now, if existing layer or layer name is given as argument
- made the docs more clear about the existing options
- added error message for wrong arguments
This fixes #74.
Please review.
Edit: And it passes all tests.

Fixed b.layer() bug to not set given layer to active

---

includes/environment.js
scripts/examples/environment/size.jsx
test/environment-tests.jsx

Allows to get the current size as an Object set the width and height with one value or set the width
and height with two values
see issue #42 
test script:  
function setup () {
doc = b.doc();
b.println('Get the size()');
b.println(b.size().toSource()); // get the height and width
b.println('set the size(100)');
b.size(100); // set width and height to 100
b.println('b.height: ' + b.height);
b.println('b.width: ' + b.width);
b.println('doc.documentPreferences.pageHeight: ' + doc.documentPreferences.pageHeight);
b.println('doc.documentPreferences.pageWidth: ' + doc.documentPreferences.pageWidth);
b.size(200,400);
b.println('b.height: ' + b.height);
b.println('b.width: ' + b.width);
b.println('doc.documentPreferences.pageHeight: ' + doc.documentPreferences.pageHeight); …

feat(size): Added document size function

---

basil.sublime-project

I usually have ESLint-Formatter running to not have to format everything by myself. I have to disable this for Basil.js because it refactors files directly on save. Please merge to make my life easier.
;-)

refactor(basil.sublime-project): Just a minor change aimed at my dev env

---

basil.js
scripts/examples/color/gradient.jsx
src/includes/color.js

The recently introduced `b.gradient()` did not work with `b.stroke()` yet (oops …). This PR fixes that and updates and improves the docs and error messages for both `b.fill()` and `b.stroke()`.
A sample of using `b.gradient()` with a stroke has been added to the `gradient.jsx` sample script.
Passes all tests.

Allowing gradients for strokes

---

basil.js
scripts/examples/shape/bounds.jsx
scripts/examples/typography/linkTextFrames.jsx
src/includes/constants.js
src/main.js

To get things going: the new `b.LOREM`.
I put it in two example scripts where I found it appropriate. There are 2 or 3 more example scripts with a lorem at the moment, but I think in those other cases we could use the upcoming `b.placeholder()` instead.
Closes #108.

Adding b.LOREM; placing it in two example scripts

---

basil.js
scripts/examples/typography/placeholder.jsx
src/includes/typography.js

As discussed in #108 this adds `b.placeholder()` which can be used to fill textFrames with InDesign's semi-random placeholder text.
Usage is simply `b.placeholder(tf);`. It also returns the generated placeholder text, so you can do
```js
var tf = b.text("Initial text", 0, 0, 100, 100);
var ph = b.placeholder(tf);
b.typo(ph, "fillColor", b.color(255, 0, 0);
```
Added an example script as well, which creates these simple sample cases:
This passes all tests. Please review. 😎

b.placeholder()

---

basil.js
scripts/examples/structure/forEach-loops.jsx
src/includes/structure.js

To somewhat prove the point that I'm not only complaining and making up issues: Here's a bug fix. 😉
This fixes the bug with text collections when using a `document` as a container as described in #116. So stuff like `b.words(b.doc())` now works again.
Additionally I added `page` as a possible container.
Here is the changes I made:
- since all the textCollection functions were basically repetitive I created one generic helper function to handle all the functionality. The original textCollection functions now only pass the type of collection to this helper function. This is cleaner and will make future changes easier as we only have to change one function, not 5.
- in all the textCollection functions I renamed `item` to `container` for clarity.
- I replaced the function …

Text collection fix

---

package.json

This adds a new npm task called release which should be run on the master branch after merging the develop branch. It re-bundles the whole lib and adds a timestamp to it.
It fixes #126

chore(bundling): add npm release task

---

basil.js
src/includes/structure.js
test/benchmarks/clearItems.jsx

This PR speeds up `b.clear()` by avoiding the internal use of `b.forEach()`. A benchmark script `clearItems.jsx` is added to `test/benchmarks/`.
On my system the benchmark gave these results:
```
Old b.clear():
Clearing 500 grouped items: 8.066 seconds.
Clearing 500 items on page: 4.259 seconds.
Clearing 500 items on layer: 6.324 seconds.
Clearing 500 items in document: 2.749 seconds.
```
```
New b.clear():
Clearing 500 grouped items: 0.275 seconds.
Clearing 500 items on page: 0.589 seconds.
Clearing 500 items on layer: 0.561 seconds.
Clearing 500 items in document: 0.453 seconds.
```
The more objects need to be deleted, the greater the speed difference. It is also greater if the objects are deleted from the active page as the page needs to be redrawn more often with the old `b.clear()`. …

Speeding up b.clear()

---

changelog.txt

The switch from github names to real ones was only in master, therefore I recreated it in develop, so the branches are not out of sync.
Additionally I just started logging the changed features (well one, so far).
I think in the future we should make this a habit to always add the change to the changelog right away if we have a PR with a new feature. That way we don't have to collect every change before a release in a hurry next time. 😉

Changed github names to real ones; logged b.clear() improvements

---

.eslintrc

This just removes a line that was accidentally left in .eslintrc and broke linting and will be merged right away.

Fixing broken .eslintrc file

---

basil.js
changelog.txt
scripts/examples/typography/styles.jsx
src/includes/shape.js
src/includes/typography.js
test/typography-tests.jsx

This greatly improves working with styles in basil.js.
1) All existing style functions (`b.paragraphStyle()`, `b.characterStyle()`, `b.objectStyle()`) are updated:
* They can now either get a style by name or the applied style of a given textObject/pageItem. If a style of a give name does not exist, it gets created. Additionally a properties name/value pairs object can be used to set the new style's properties or to update an existing style's properties.
2) The new functions `b.applyParagraphStyle()`, `b.applyCharacterStyle()` and `b.applyObjectStyle()` are added. They take a textObject|textFrame|Story/pageItem and apply the given style to it. The style can be given as style instance or by name.
3) The example script `styles.jsx` is added to demonstrate how to use the style functions. …

Expanding functionality of styles

---

install.bat

Quick fix of the paths in install.bat .
The file will be reworked soonly by @fabianmoronzirfas, but it does not hurt to fix the wrong paths right now, I guess.
Fixes #156.

Fixing paths in install.bat

---

.gitignore

This adds the user folders `libraries/` and `sketches/` to `.gitignore` as with basil.js's new location the developer's environment is now on the same directory level as the user's environment. (See #155)
+ Some minor cleanup, removal of obsolete paths and making syntax more consistent.

.gitignore - Added user folders + minor cleanup

---

.eslintrc
scripts/.eslintrc

*sigh my description got lost again*
This adds an additional `.eslintrc` to `scripts/` to overwrite three roots of the main `.eslintrc` as discussed in #159.
Also adds `HashList` to globals in the main `.eslintrc`.

Scripts eslint

---

basil.js
changelog.txt
src/includes/data.js
test/data-tests.jsx

During working on another function I noticed that instances of multiple text objects (`Characters`, `Words`, `Lines`) are not recognized by `b.isText()`.
This means that until now this happened:
```js
var tf = b.text(b.LOREM, 0, 0, 200, 200);
var w = b.words(tf);
b.println(w); // --> [object Words]
b.println(b.isText(w)); // --> false
```
This PR fixes this, so collections of multiple Word objects evaluate to true with `b.text()`.
The reason this needs to be evaluated via `obj.constructor.name` instead of `obj instanceof` is that `obj instanceof Characters` etc. throws a reference error if there was not yet an `[object Characters]` defined during script execution.
The order of the checks was slightly altered to improve performance.
Tests for all possible cases were added. It also passes …

b.isText() fix to correctly identify multiple text objects

---

basil.js
src/includes/public-vars.js
src/includes/shape.js

Making attributes consistent and improving function descriptions as discussed in #171.
Please review, if this was done correctly.
Closes #174.

jsDoc corrections

---

src/includes/shape.js

minor change. Only for the beauty of the docs.  
(Did you know there is a user called `@todo`?)

found a TODO made it a `@todo`

---

basil.js
src/includes/shape.js

Came across this while creating Sublime snippets for basil.js. The parameters for `b.vertex()` are named incorrectly. The optional parameters for the handles are named `xAnchorLeft` etc., while the term "anchor" actually always refers to the center node of a bezier node, not the handles.
So, I think this should be more correct and more intuitive to understand.
Please have a look, if this change is ok.

Renamed vertex params from *anchor* to *handle*

---

basil.js
changelog.txt
src/includes/core.js
src/includes/typography.js
test/typography-tests.jsx

As discussed in #119, `b.textFont()` does no longer stop the script if a font is missing, but gives a warning instead.
It looks like this:
```js
b.textFont("myFont", "Bold"); // ### Basil Warning -> b.textFont(), font "myFont  Bold" not installed. Using current font instead.
```
It handles cases where a font *is* installed, but does not have any default font style (Regular/Normal/Roman/Book), like this:
```js
b.textFont("Erbar"); // ### Basil Warning -> b.textFont(), font "Erbar  Regular" not installed. Using current font instead.
```
If it does not find the font, it will use the current font instead, which is either the default font or the most recently applied font (if a font has previously been set successfully).
Btw., although it might not look like it from the code, this *does* work …

Rewrote b.text() so it won't stop a script anymore if font is missing

---

basil.js
changelog.txt
src/includes/constants.js
src/includes/core.js

As discussed in #123, this adds a constant `b.SCRIPTNAME` that holds the name of the script. This will change the welcome text from the current
```Running in basil.js 1.1.0 ...```
to
```Running ellipses.jsx using basil.js 1.1.0 ...```
Also, it will add the name of your script to the undo menu:
As you can see, I left the file extension in there, because I was trying it out a bit and it felt weird if it's missing:
I think it might not be obvious right away that his refers to a script named `ellipses`. As opposed to this:
I think here you understand much better that this refers to the script. Also, we can always use basil's own `b.split()` method to retrieve the script's name without extension:
```var scriptNameWithoutExtension = b.split(b.SCRIPTNAME, ".")[0]```
Let me know, if you disagree. …

b.SCRIPTNAME

---

basil.js
changelog.txt
src/includes/core.js
src/includes/environment.js
src/includes/structure.js
test/environment-tests.jsx

This adds `b.revert()` as proposed and discussed in #133.
As a reminder: This is useful during the development stage of a script, if you don't want to reset a document manually each time before you run the script (`b.clear(b.doc())` would not work in many cases, as it does not clear new layers and colors etc.)
So while developing your script, it would simply look like this:
```js
// @includepath "~/Documents/;%USERPROFILE%Documents";
// @include "basiljs/basil.js";
function draw() {
b.revert();
// all code that you are developing here
}
b.go();
```
And this would work both for saved and unsaved documents.
I did some testing and figured out that it is actually much quicker to close the document without saving and re-opening it than use InDesign's actual `doc.revert()` method, so I went …

Adding b.revert()

---

basil.js
changelog.txt
src/includes/constants.js
src/includes/environment.js
test/environment-tests.jsx

Hey there,
just had the idea that it would be nice if instead of using values to set the page size with `b.size()`, you could also set the size with the name of a page size preset like `"A4"` or `"Letter"`, etc.
Was easy to implement, so I decided to create a pull request right away. Hope the idea makes sense to you guys as well.
However, before anybody goes ahead to merge this, one question: Should we also allow yet another parameter to set the orientation? With the implementation I just did, it simply keeps the orientation. That means if I have a landscape `A4` document and set it to `iPhone` format via `b.size("iPhone")` I will get a landscape iPhone sized document automatically.
Should we allow an extra parameter like `b.PORTRAIT` and `b.LANDSCAPE` (in which case I would create a new …

Added possibility to use a page size preset as argument for b.size()

---

basil.js
src/includes/environment.js

I just came across these two functions and the docs were seriously messed up/mixed together (In the auto generation of docs (two `b.group()` methods were created due to a wrong `@method` parameter and lots of other stuff).
So, here are the improvements:
- Fixed and improved the docs
- Made error messages more understandable
- Added additional error checking if strings of non-existing groups are given
- Cleaned up the methods
This does not really change anything in functionality (except the doc generation), so a quick review should do.

Fixing b.group() and b.ungroup()

---

basil.js
src/includes/data.js

A quick fix to add some parameter checks for `b.startsWith()` and `b.endsWith()` as described in #213. Quick review anyone.? :)

Improved error handling for b.startsWith() and b.endsWith()

---

basil.js
changelog.txt
src/includes/shape.js

This adds the option to draw your rects with rounded corners.
This
```js
b.noFill();
b.rect(30, 20, 80, 55);
b.rect(30, 90, 80, 55, 20);
b.rect(30, 160, 80, 55, 20, 15, 10, 5);
```
turns into this
So as Fabian summed up nicely [here](https://github.com/basiljs/basil.js/issues/214), syntax is:
```
Syntax	
b.rect(a, b, c, d)
b.rect(a, b, c, d, r)
b.rect(a, b, c, d, tl, tr, br, bl)
Parameters	
a	float: x-coordinate of the rectangle by default
b	float: y-coordinate of the rectangle by default
c	float: width of the rectangle by default
d	float: height of the rectangle by default
r	float: radii for all four corners
tl	float: radius for top-left corner
tr	float: radius for top-right corner
br	float: radius for bottom-right corner
bl	float: radius for bottom-left corner
```
Please review. 🔍 🐛 …

b.rect() with rounded corners

---

basil.js
changelog.txt
src/includes/shape.js
src/includes/typography.js

This PR fixes the following:
- Adds the `b.RADIUS` option for `b.rectMode()` (for some reason this was missing, although it was mentioned in the docs?).
- Makes `b.rectMode()` work for text frames as well (as we agreed on [here](https://github.com/basiljs/basil.js/issues/145)). This makes working with both text frames and rectangles much more intuitive, as they are drawn in the same way.
- Updates, improves and fixes docs for `b.rectMode()`, `b.ellipseMode()`, `b.text()`.
Please review! 🔍 🐛

Shape Mode fixes

---

basil.js
src/includes/environment.js

Fixing ungroup method name in docs.

Fixing wrong method name

---

basil.js
src/includes/data.js

This fixes `b.trimWord()` to actually trim all punctuation from the word's beginning and end (see #230).
RegEx might look a bit scary, but it works. Also updated the source, as not to give the impression that I know anything about RegEx. 😉

Improving trim word to trim all sorts of punctuation

---

basil.js
src/includes/data.js

Reverts basiljs/basil.js#228
Reverting this change, because I did not fully think this through. 😉
(new version did not work with `null` or `undefined` as input)

Revert "Simplified isString"

---

basil.js
src/includes/document.js

This fixes the page function and makes it work with actual page names. So, if your pages are using non-standard numbers (such as A, B, C or i, ii, ii), you can target them with `page("A")`.
It also improves error handling and allows to return a page for page items that are placed on the pasteboard.
Docs are improved and a few examples for usage are added for the docs.
This is intended to prepare for the addition of master page functionality.

page() fixes

---

basil.js
changelog.txt
src/includes/constants.js
src/includes/document.js

This adds the new function `applyMasterPage` as the first function to introduce master page abilities to basil.
Syntax is `applyMasterPage(page, master)`, so it can be used like this:
```js
applyMasterPage(page(), "A");  // applies master with prefix "A" to current page
applyMasterPage(3, "A-Master"); // applies master with full name "A-Master" to doc's third page
applyMasterPage("IV", NONE); // applies the [None] master to the page named "IV" and thus removes the previous master
```
Also with this PR, private methods `getPage()` and `getAndUpdatePage()` were introduced to allow for finer control when retrieving pages (not always do we need/want to jump to the page we get).

applyMasterPage()

---

basil.js
src/includes/document.js

There was an error introduced by my recent page and master page additions/fixes:
`addPage()` did not jump to the newly added page anymore. This fixes it and also fixes return values for `nextPage()` and `previousPage()`.

Fixing page functions to return page objects and to jump to new page

---

basil.js
changelog.txt
src/includes/data.js
src/includes/document.js
test/all-tests.jsx
test/document-tests.jsx

This standardizes and cleans up the collection functions (e.g., `words()`, `characters`, `items()` etc.) and adds two new ones: `graphics()` and `textStyleRanges()`.
Changes in detail:
- collection functions now always return collections (or arrays), also when a callback function is used
- if a callback functions is used that returns falls at some point and interrupts the loop, a collection of elements up to that point is returned
- same behaviour goes for `forEach()`
- legal containers were made more consistent between functions and additional possible containers were added for many functions (e.g., words on a layer, words in a group, items in a paragraph etc.)
- docs were improved to be easier to understand (I hope)
- internal cleanup, including the removal of private function …

Rework of collection functions + graphics() + textStyleRanges()

---

basil.js
changelog.txt
src/includes/shape.js
test/shape-tests.jsx

As described in #291 .
Cleaned up the test file a bit as well, and renamed it to be aligned better with our file names.<

vertex path: move CLOSE argument from beginShape() to endShape()

---

basil.js
src/includes/data.js
test/data-tests.jsx
test/document-tests.jsx

Fixed the `isArray()` issue described in #290. Added tests for `isArray()`. Will merge right away.

Fixed isArray() to also handle allPageItems, allGraphics etc.

---

basil.js
changelog.txt
src/includes/shape.js

In the effort to make basil.js more similar to p5.js and Processing, this adds the shape functions `point()`, `triangle()` and `quad()`, which should be all really self explanatory.
Additionally this allows for a three parameter input for `ellipse()` if the user wants to create a circle.
Will merge this right away.

point(), quad() and triangle()

---

basil.js
src/includes/document.js

Allows to use `selection()` as setter as explained in #238 .

selection() as setter

---

basil.js
src/includes/data.js
test/all-tests.jsx

This fixes a bug that I introduced recently to `isArray()` that made it not work for `undefined` and `null` values anymore. Subsequently the `transform()` function was broken for some transforms. This is all fixed now. Will merge right away.

Fixing isArray() and functions that depended on it

---

basil.js
src/includes/typography.js

This allows to use `typo()` for text on path as well. Fixes #309, will merge right away.

typo() for path text

---

basil.js
src/includes/image.js
src/includes/input.js

This fixes the issue described in #303, so the functions `loadString()`, `loadStrings()` and `image()` can now also load files via file path string inputs that are not in the data folder.
That also allows to specify paths without having the document saved first (was necessary before, since a data folder path was assumed).

Absolute file paths for input functions

---

basil.js
src/includes/color.js

This introduces a private function for three of the color functions (`stroke()`, `fill()` and soon `background()` to retrieve a swatch via the `color()` function. Makes the internal code cleaner, from the user perspective everything works just like before.

Clean up of color functions

---

basil.js
src/includes/document.js

Quick fix for `selection()` to work again with no arguments. Will merge right away.

selection() works again with no arguments

---

basil.js
changelog.txt
src/includes/document.js

This fixes `guideX()` and `guideY()` to place guides correctly when using any canvas modes other than `PAGE`. Additionally, this sets the guideY's `fitToPage` property to `false` when in any of the facing canvas modes, so the guide will cross the entire spread (as is to expected in these modes).

Fix for guides functions

---

basil.js
src/main.js

Removed the loop condition from this initial removal of global variables as it was disallowing chaining of basil scripts from other scripts.
This should not cause any issues I think, however, if you *do* encounter some issues with this, let me know, then I'll have to reverse it or think of something else.

Initial removal of global variables without loop condition
